# See https://docs.aspect.build/v/workflows/config
---
tasks:
  - format:
      queue: aspect-small-amd64
  - buildifier:
      queue: aspect-small-arm64
  - configure:
      queue: aspect-small-arm64
  - test:
      hooks:
        - type: before_task
          command: vmstat -a -S M -t 5 2>&1 > /tmp/vmstat_out &
        - type: after_task
          command: cat /tmp/vmstat_out
  - delivery:
      auto_deliver: true
      branches:
        - main
  - branch_freshness:
      hooks:
        - type: before_task
          command: if [ -e .git/rebase-apply ]; then rm -rf .git/rebase-apply && echo "Cleaning up .git/rebase-apply!"; fi && git status
        - type: after_task
          command: git status
