# See https://docs.aspect.build/v/workflows/config
---
queue: govcloud-default
tasks:
  - format:
  - buildifier:
  - configure:
  - test:
      hooks:
        - type: before_task
          command: vmstat -a -S M -t 5 2>&1 > /tmp/vmstat_out &
        - type: after_task
          command: cat /tmp/vmstat_out
  - delivery:
      auto_deliver: true
      branches:
        - main
        - CaerusKaru-patch-1
