# See https://docs.aspect.build/v/workflows/config
---
tasks:
  - format:
      queue: aspect-small-amd64
  - buildifier:
      queue: aspect-small-arm64
  - configure:
      queue: aspect-small-arm64
  - test:
  - delivery:
      always_deliver: true
      bazel:
        flags:
          - --remote_download_outputs=toplevel
      branches:
        - main
        - delivery_bwotb_test
